"use strict";
exports.__esModule = true;
var cors = require("cors");
require('dotenv').config();
var express = require("express");
var path = require("path");
var app = express();
app.use(cors());
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
var port = Number(process.env.PORT) || 4444;
var distPath = path.resolve(__dirname + "../../../dist");
app.use(express.static(distPath));
var routes_1 = require("./routes");
app.use(routes_1["default"]);
app.get('/*', function (req, res) {
    res.sendFile(distPath + '/index.html');
});
app.listen(port);
console.log("App listening on " + port);
